### ISSUE TITLE
Any detail tutorials available?

### ISSUE THREAD

**Issue by tejasklodha** [balassy/iot-interaction-pack#15]
Dear Sir,

Any detail tut available?
Like If I want to Use RFID code then what is schematic circuit diagram?

Thnaks,

**Comment by balassy** [comment]
Hey Tejas,

I'm sorry, I don't have a circuit diagram because depending on what Arduino board and what Windows IoT Core device you use it must be different. This is the basic concept:

- First connect the RFID-RC522 to your Arduino board. There is no specialty here, so depending on what type of Arduino board you have, you can google for the wiring. The Arduino will be responsible for scanning the RFID card.

- Connect the Arduino board to your Windows IoT Core device (e.g. Raspberry PI) via I2C. This requires two wires, and again, depending on the exact Arduino and Windows IoT Core devices, the wiring must be slightly different. The I2C channel will be used to transfer the scanned data from the Arduino to the Windows IoT Core device.

- Finally connect an output GPIO pin of the Arduino to in input GPIO pin of the Windows IoT Core device. The Arduino will use this connection to signal that a card has been scanned, and the Windows device will retrieve the content of the previous read card from the Arduino.

I know this is not a circuit diagram, but if you tell the exact boards you use, I can try to be more specific with the pins.

Hope this helps,
György
